name: "Cache dependencies"
description: "Cache and install Node.js dependencies"
runs:
  using: "composite"
  steps:
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ env.CACHE_KEY }}-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      run: npm ci
      shell: bash
